[package]
name = "mindlock"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9.6"
gdk-pixbuf = "0.20"
gio = "0.20"
glib = "0.20"
reqwest = "0.11"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
